// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBUBBVEcl0DbZ_BKFhEZJ11gvFUZbEfKI',
    appId: '1:557448715527:web:22cc0bba7e228147b8b9a2',
    messagingSenderId: '557448715527',
    projectId: 'spotify-620d8',
    authDomain: 'spotify-620d8.firebaseapp.com',
    storageBucket: 'spotify-620d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyPXm8SipGinSOhMSMkReJ9WWECmBB7o0',
    appId: '1:557448715527:android:becc4a64c22eb65eb8b9a2',
    messagingSenderId: '557448715527',
    projectId: 'spotify-620d8',
    storageBucket: 'spotify-620d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_H3RG30f3klv7N2NtXRwJCy2spEopajs',
    appId: '1:557448715527:ios:7d058ba17d23af36b8b9a2',
    messagingSenderId: '557448715527',
    projectId: 'spotify-620d8',
    storageBucket: 'spotify-620d8.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_H3RG30f3klv7N2NtXRwJCy2spEopajs',
    appId: '1:557448715527:ios:7d058ba17d23af36b8b9a2',
    messagingSenderId: '557448715527',
    projectId: 'spotify-620d8',
    storageBucket: 'spotify-620d8.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBUBBVEcl0DbZ_BKFhEZJ11gvFUZbEfKI',
    appId: '1:557448715527:web:fd5f92ee16d72aecb8b9a2',
    messagingSenderId: '557448715527',
    projectId: 'spotify-620d8',
    authDomain: 'spotify-620d8.firebaseapp.com',
    storageBucket: 'spotify-620d8.appspot.com',
  );

}